In [1]:
import numpy as np

# THE BASICS

In [2]:
a=np.array([1,2,3])

In [3]:
print(a)

[1 2 3]


In [4]:
a.ndim #Get Dimension

1

In [5]:
a.shape #get shape

(3,)

In [6]:
a.dtype #Get type

dtype('int64')

In [14]:
b = np.array([1.2,2.4,3.6,4.2,5.4,6.1], dtype='int32') #specify the data type

In [15]:
b.dtype

dtype('int32')

In [16]:
b.itemsize #How many Bites

4

In [18]:
b.size

6

In [19]:
b.size * b.itemsize #Get total size i.e. number of bites

24

In [21]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [22]:
a.shape 

(2, 7)

In [23]:
#get specific element [r,c] Recall indexing in Python starts at 0
a[1,5]

13

In [32]:
#Get a specific row
a[0,1:6]

array([2, 1, 4, 5, 6])

In [25]:
#Get a specific column
a[:,2]

array([ 3, 10])

In [27]:
# [ startindex : endindex : stepsize ]
a[0, 1:6:2]

array([2, 4, 6])

In [28]:
#Changes 
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [30]:
a[:,2]=[1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [35]:
a[1,2:6] 

array([ 2, 11, 12, 20])

In [40]:
#All zeros matrix
np.zeros((2,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [42]:
#All ones
np.ones((3,2,3), dtype='int32')

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]], dtype=int32)

In [43]:
#any other value
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [44]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [45]:
#Random decimal numbers
np.random.rand(4,2)

array([[0.38617425, 0.9617019 ],
       [0.12267234, 0.53442832],
       [0.77113589, 0.72545062],
       [0.33589764, 0.55433601]])

In [48]:
np.random.rand(5,2,3)

array([[[0.7442574 , 0.46089936, 0.82951427],
        [0.40790636, 0.6749494 , 0.49448667]],

       [[0.75636887, 0.60868182, 0.95820266],
        [0.10657762, 0.52001451, 0.61914981]],

       [[0.25885227, 0.51784782, 0.96721907],
        [0.1819617 , 0.03002997, 0.21529714]],

       [[0.40643379, 0.81630211, 0.51776249],
        [0.17161388, 0.76142362, 0.81162391]],

       [[0.20238231, 0.53831672, 0.97027909],
        [0.18630548, 0.72920581, 0.15948714]]])

In [49]:
np.random.random_sample(a.shape)

array([[0.36427378, 0.47196377, 0.39624949, 0.88486775, 0.62323469,
        0.39077039, 0.17371532],
       [0.43070592, 0.73968232, 0.15306981, 0.93533548, 0.28124352,
        0.89366435, 0.32773319]])

In [60]:
#Random integer values top 7 is exculsive
np.random.randint(-4,7, size=(3,3))

array([[-3, -4,  0],
       [ 1,  6,  6],
       [ 1,  1, -1]])

In [63]:
np.identity(4) #identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [64]:
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [67]:
arr = np.array([[1,2,3]]) #makes each entry a row
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [71]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1]=9
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [73]:
output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [98]:
np.linalg.det(output)

0.0

In [75]:
#Be careful when copying 
a = np.array([1,2,3])
b=a
print(a)

[1 2 3]


In [76]:
b[0]=100
print(b)

[100   2   3]


In [77]:
print(a) #when we point to a when we change a value in b we change calue in a

[100   2   3]


In [78]:
#we can however
b=a.copy()
print(b)

[100   2   3]


# MATHEMATICS

In [79]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [80]:
a - 2

array([-1,  0,  1,  2])

In [81]:
a +2

array([3, 4, 5, 6])

In [82]:
a * 2

array([2, 4, 6, 8])

In [83]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [84]:
b = np.array([1,0,1,0])

In [85]:
a+b

array([2, 2, 4, 4])

In [86]:
a **2

array([ 1,  4,  9, 16])

In [87]:
#Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [88]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# LINEAR ALGEBRA

In [93]:
a = np.ones((2,3))
b = np.full((3,2),2)

In [96]:
print(a)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [97]:
#Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

# STATISTICS

In [99]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
np.min(stats,axis=1)

array([1, 4])

# Reorganizing Arrays

In [105]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [106]:
after=before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [107]:
after=before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [109]:
#Vertically Stacking Vectors/Matricies
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [110]:
np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [113]:
#Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# MISCALLENEOUS

In [120]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [121]:
#where in File data is >50

filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [122]:
#index the necessary
#You can index with a list in numpy
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [123]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [124]:
#If any of the values of the Cols are greater than 50?
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [127]:
np.any(filedata > 50, axis=1)

array([ True,  True,  True])

In [129]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [130]:
h = np.array